{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shelfdb.serviceAccountName" . }}
  labels:
{{ include "shelfdb.labels" . | indent 4 }}
{{- end -}}
