name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run fmt
      run: cargo +nightly fmt --check
    - name: Run tests
      run: cargo test
    - name: Run fmt
      run: cargo +nightly cargo
