name: Build

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run fmt
      run: cargo +nightly fmt --check
    - name: Run tests
      run: cargo test
    - name: Run fmt
      run: cargo +nightly cargo
