name: Deploy Nightly

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --tag joatin/shelfdb:$(date +%s) --tag joatin/shelfdb:nightly
      - name: Push docker image
        run: docker psuh joatin/shelfdb:$(date +%s)
