name: Deploy Nightly

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: DOCKER_BUILDKIT=1 docker build . --tag joatin/shelfdb:nightly
      - name: Docker login
        run: docker login -u joatin -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push docker image
        run: docker push joatin/shelfdb:nightly
